### ISSUE TITLE
Wrong http methods cannot return 405

### ISSUE THREAD

**Issue by soenkehahn** [alpmestan/servant#10]
Ideally, servant servers would be able to return a 405 when a method is not allowed. In our current design `RoutingApplication`s can just reject `Request`s (by returning `Nothing`) which will result in a `404`. I'm not sure how to fix this properly though.

**Comment by alpmestan** [comment]
So you want to enrich that `Maybe` with some more informative data about why a route has been abandonned?

**Comment by soenkehahn** [comment]
That would be a possibility, although it doesn't sound too easy to implement.

Also, I wonder how important this is in practice.

**Comment by alpmestan** [comment]
``` haskell
data RouteMismatch =
    NotFound
  | WrongMethod
  -- | IncorrectArguments  ?
```

and replace the `Maybe a` with `Either RouteMismatch a`? So that at the very end, if we're done testing all the possible paths, depending on what `RouteMismatch` we get, we can answer appropriately?

**Comment by soenkehahn** [comment]
Here we have something like `<|>` semantics: https://github.com/zalora/servant/blob/new-impl/servant/src/Servant/API/Union.hs#L17. How would that be implemented for `Either RouteMismatch a`? In other words, if for two alternative routes one reports `NotFound` while the other reports `WrongMethod` what do we report?

**Comment by alpmestan** [comment]
``` haskell
instance Monoid RouteMismatch where
  mempty = NotFound

  NotFound `mappend` x = x
  WrongMethod `mappend` _ = WrongMethod
```

And we only emit `WrongMethod`s from the terminal bits of an endpoint (i.e a `Delete`, `Get`, `Post` or `Put` node) in case the pathInfo is empty (has been entirely "consumed") but the method doesn't match. Once we get one, it infects the whole combination of routes and will pop up at the top routing call.

``` haskell
newtype RouteResult a = RR (Either RouteMismatch a)
  deriving (Eq, Show)

-- | If an endpoint matches exactly, we return its response
--   otherwise we just use the `RouteMismatch` monoid
--   to figure out whether we made a perfectly fine request
--   except for the method that we used
instance Monoid (RouteResult a) where
  mempty = RR $ Left mempty

  RR (Left x) `mappend` RR (Left y) = RR $ Left (x <> y)
  RR (Left _) `mappend` RR (Right y) = RR $ Right y
  RR (Right x) `mappend` _ = RR $ Right x
```

What do you think?

**Comment by soenkehahn** [comment]
That looks promising!

About `IncorrectArguments`: I thought about this too. (I'm assuming you're thinking of something like a missing or unparseable `GetParam`.) But I don't think this should be solved here. If the `GetParam` is missing or unparseable, the corresponding endpoint should take care of that (and throw a `400` or whatever). So this doesn't interfere with your approach.

Basically we have two reasons, why a `RoutingApplication` may refute a request, and cause alternative routes to be tried: `NotFound` and `WrongMethod`. All other failures (wrongly typed body, missing or wrongly typed parameters) don't cause alternative endpoints to be tried, but the endpoints have to report an error. At least that's my proposal.

(`NotFound` can be caused by both `"path" :> something` and `Capture "param" SomeType :> something`.)

**Comment by alpmestan** [comment]
See the commit right above. It also modifies a test to check that `405` is fired when we `POST` to a `GET` endpoint that otherwise matches the route (and hence only differs in the method).
