### ISSUE TITLE
Should fields from the request body be available (similar to GetParam)?

### ISSUE THREAD

**Issue by soenkehahn** [alpmestan/servant#11]
Some (most?) web-frameworks allow to look up parameters from the request body. This is mostly used with url-encoded bodies (I think), which we don't support. Do we want to allow to look up parameters from the fields of a JSON object sent in the request body?

(This would somehow clash with `RQBody`, but I don't see any real problems, even if used for the same endpoint.)

We could also have a mechanism for looking up parameters in both get and request body parameters.

cc: @alpmestan @jkarni

**Comment by alpmestan** [comment]
1/ Do you think we should also support URL-encoded bodies? I'm not sure we want that, but would like to hear your opinions (both of you) too.

2/ Regarding looking up precise parameters à-la `GetParam` but in the (JSON) request body, yeah why not. I mean, I don't really think I'd use it all that much, but that somehow enables rapid prototyping I guess. It extends the vocabulary so why not :-) It won't really clash with `RQBody`: the latter is "give me the whole json body as this type" whereas your suggested `JsonParam` (any better name?) is just "look up this key in the JSON object you can see in the request body".

3/ Having the "look up in GET params and if it fails lookup in the json body" mechanism would be nice indeed. We could call it just `Param` maybe?

**Comment by soenkehahn** [comment]
I like `Param` for looking in both url query and body for matching parameters.

I think better than `JsonParam` is something like `BodyParam` (or `PostParam` analog to `GetParam`?). It would figure out whether it's JSON, url-encoded or even xml by the body itself and the `Content-Type` header. (Same for `Param`.)

In any case, I think we should implement this when someone needs any of this. So, please, comment here if you do!

**Comment by soenkehahn** [comment]
I would propose either (`GetParam` and `PostParam`) **or** (`QueryParam` and `BodyParam`).

**Comment by alpmestan** [comment]
I'd prefer the second combination of names: `QueryParam` and `BodyParam`. Can I go ahead and implement it?

**Comment by alpmestan** [comment]
By the way, I'd suggest renaming `RQBody` (as it is now) to `JsonBody`.

**Comment by jkarni** [comment]
I don't think we should do this. For `BodyParam` for instance, the client code can simply create a type with a `FromJSON` instance that has the params they would have used `BodyParam` for, and that (a) is just as type safe, (b) is more familiar, and (c) doesn't bloat even more our API types

**Comment by alpmestan** [comment]
Sounds good to me as well. Like I said on the chat, if we don't put the whole plan to action, can we transform this into a PR for renaming `GetParam` to `QueryParam` and `RQBody` to `JsonBody`?

**Comment by soenkehahn** [comment]
:+1: for the renaming.
