### ISSUE TITLE
Dead links in the README

### ISSUE THREAD

**Issue by soenkehahn** [alpmestan/servant#4]
The links for the haddock documentation of `servant`, `servant-pool`, etc. give me 404s.

**Comment by sol** [comment]
Is this due to the Hackage build being broken?

**Comment by fmap** [comment]
No, the referenced Haddock's were hosted on @alpmestan's server, see the URIs. Update references to point at Hackage?

http://hackage.haskell.org/package/servant
http://hackage.haskell.org/package/servant-pool
http://hackage.haskell.org/package/servant-postgresql
http://hackage.haskell.org/package/servant-response
http://hackage.haskell.org/package/servant-scotty

**Comment by alpmestan** [comment]
Oops, yeah, I moved my server to another machine (running NixOS :+1:) since then. I can just point to the hackage haddocks now anyway, since all these libraries have been released. Fixing this right away.
