### ISSUE TITLE
servant-pool links to non-existant homepage url

### ISSUE THREAD

**Issue by peti** [alpmestan/servant#40]
http://github.com/zalora/servant-pool doesn't exist.

**Comment by alpmestan** [comment]
Hey,

For this and for #41 we've submitted a PR to nixpkgs a few minutes ago (see [here](https://github.com/NixOS/nixpkgs/pull/5311)). Thanks for reporting that, we forgot to update the nixpkgs packages.

**Comment by jkarni** [comment]
nix now has the new versions of servant - closing
